Repository volvoEnc/biba-bot, pull requests merged in 2020-08, with the labels that each got.

#4 fix .gitignore file
  .gitignore
Labels: bugfix

#6 bugfix/BIBABOT-2: -
  actions/BigBibonAction.js
Labels: bugfix

#7 bugfix/BIBABOT-3: -
  app/router.js
Labels: bugfix

#10 bugfix/BIBABOT-5: -
  actions/fap_bibaAction.js
Labels: bugfix

#14 feature/BIBABOT-3: -
  controllers/fapController.js
  views/error.pug
Labels: feature

#16 feature/BIBABOT-4: -
  controllers/topController.js
  models/User.js
  routes.js
  views/rating/bigbons_rating.pug
Labels: feature

#9 feature/BIBABOT-2: -
  actions/fap_bibaAction.js
  controllers/fapController.js
  views/fap.pug
  views/fap_end.pug
Labels: feature

#15 bugfix/BIBABOT-8: -
  actions/fap_bibaAction.js
  controllers/fapController.js
Labels: bugfix

#12 Bugfix/bibabot 7
  actions/fap_bibaAction.js
  controllers/fapController.js
  views/error.pug
Labels: bugfix

#11 bugfix/BIBABOT-6: -
  actions/fap_bibaAction.js
  controllers/fapController.js
  views/error.pug
Labels: bugfix

#5 Feature/bibabot 1
  app/router.js
  controllers/battleController.js
  controllers/shopController.js
  controllers/testController.js
  events/DeleteExpiredSessions.js
  main.js
  models/Catalog.js
  models/Inventory.js
  models/Session.js
  models/User.js
  routes.js
  routes/command.js
  routes/session.js
  shop/products/ChanceProduct.js
  shop/products/ConsumablesProduct.js
  views/app/mailing.pug
  views/shop/categories.pug
  views/shop/product.pug
  views/shop/shop_message.pug
Labels: feature

#18 Feature/bibabot 5
  actions/BigBibonAction.js
  actions/fap_bibaAction.js
  controllers/battleController.js
  controllers/bibaController.js
  models/Top.js
  routes/command.js
  views/profile/mytop.pug
  views/profile/profile.pug
Labels: bugfix, feature
