Repository volvoEnc/biba-bot, pull requests merged in 2021-02, with the labels that each got.

#29 feature 9 - Пассивная биба
  views/Other/hello.pug
  views/Other/hello_angry.pug
  views/StartBattle.pug
  views/StartBattle_angry.pug
  views/battle.pug
  views/battle_angry.pug
  views/biba_who.pug
  views/biba_who_angry.pug
  views/big_biba/end.pug
  views/big_biba/end_angry.pug
  views/big_biba/start.pug
  views/big_biba/start_angry.pug
  views/big_biba/step_1.pug
  views/big_biba/step_10.pug
  views/big_biba/step_10_angry.pug
  views/big_biba/step_11.pug
  views/big_biba/step_11_angry.pug
  views/big_biba/step_12.pug
  views/big_biba/step_12_angry.pug
  views/big_biba/step_1_angry.pug
  views/big_biba/step_2.pug
  views/big_biba/step_2_angry.pug
  views/big_biba/step_3.pug
  views/big_biba/step_3_angry.pug
  views/big_biba/step_4.pug
  views/big_biba/step_4_angry.pug
  views/big_biba/step_5.pug
  views/big_biba/step_5_angry.pug
  views/big_biba/step_6.pug
  views/big_biba/step_6_angry.pug
  views/big_biba/step_7.pug
  views/big_biba/step_7_angry.pug
  views/big_biba/step_8.pug
  views/big_biba/step_8_angry.pug
  views/big_biba/step_9.pug
  views/big_biba/step_9_angry.pug
  views/error.pug
  views/error_angry.pug
  views/events.pug
  views/events_angry.pug
  views/fap.pug
  views/fap_angry.pug
  views/fap_end.pug
  views/fap_end_angry.pug
  views/profile.pug
  views/profile/mytop.pug
  views/profile/notifications.pug
  views/profile/notifications_angry.pug
  views/profile/profile.pug
  views/profile/profile_angry.pug
  views/profile/register.pug
  views/profile/register_angry.pug
  views/profile/stata.pug
  views/profile_angry.pug
  views/rating/coins_rating.pug
  views/rating/coins_rating_angry.pug
  views/rating/local_coins_rating.pug
  views/rating/local_coins_rating_angry.pug
  views/register.pug
  views/register_angry.pug
Labels: feature

#30 BIBABOT-12: shop completed
  app/core.js
  app/router.js
  controllers/BigBattleController.js
  controllers/appController.js
  controllers/battleController.js
  controllers/bibaController.js
  controllers/rulesController.js
  controllers/shopController.js
  events/DeleteConversationsEvent.js
  events/mainEvent.js
  main.js
  models/Catalog.js
  models/Inventory.js
  models/Rules.js
  models/User.js
  routes/command.js
  shop/products/ChanceProduct.js
  shop/products/CoinProduct.js
  shop/products/ConsumablesProduct.js
  views/app/errors.pug
  views/app/help.pug
  views/shop/shop_message.pug
Labels: bugfix, feature

#34 bugfix/BIBABOT-15: fix bugs
  views/profile/mytop.pug
  views/rating/coins_rating_angry.pug
  views/rating/local_coins_rating_angry.pug
Labels: bugfix
